version: '3.1'
services:
  teamspeak:
    image: teamspeak
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
      TS3SERVER_SERVERADMIN_PASSWORD: test
