name: Main Workflow for TS3Dashboard
on: [ push ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      teamspeak:
        image: teamspeak
        ports:
          - 9987:9987/udp
          - 10011:10011
          - 30033:30033
        env:
          TS3SERVER_LICENSE: accept
          TS3SERVER_SERVERADMIN_PASSWORD: test
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn test
