name: Main Workflow for TS3Dashboard
on: [ push ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      teamspeak:
        image: teamspeak
        ports:
          - 9987:9987/udp
          - 10011:10011
          - 30033:30033
        env:
          TS3SERVER_LICENSE: accept
          TS3SERVER_SERVERADMIN_PASSWORD: test
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn test
