name: Main Workflow for TS3Dashboard
on: [ push ]
jobs:
  test-fronted:
    name: Test Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Test
        run: cd frontend && npm test -- --watchAll=false

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    services:
      teamspeak:
        image: teamspeak
        ports:
          - 9987:9987/udp
          - 10011:10011
          - 30033:30033
        env:
          TS3SERVER_LICENSE: accept
          TS3SERVER_SERVERADMIN_PASSWORD: test
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: TS_ADDRESS=teamspeak mvn test
